version: "3"

services:
   logstash:
      #build:
         #context: .
         #dockerfile: dockerfile
      image: docker.elastic.co/logstash/logstash:7.15.0-amd64
      labels: 
         author: "VECTRA Consultoria e Serviços"
      container_name: logstash
      #environment:
      #   XPACK.MONITORING.ELASTICSEARCH.USERNAME: ${ELASTIC_USER}
      #   XPACK.MONITORING.ELASTICSEARCH.PASSWORD: ${ELASTIC_PASSWORD}
      #   XPACK.MONITORING.ELASTICSEARCH.HOSTS: http://elastic:9200
      restart: on-failure
      volumes:
         - ./lib:/mnt
         - ./titanic-dataset:/usr/share/logstash/titanic-dataset
         - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
         - ./config/pipeline.yml:/usr/share/logstash/config/pipeline.yml
         #- ./config/sql_last_value:/usr/share/logstash/config/sql_last_value:rw
      ports:
         - 5044:5044
      networks: 
         - elastic

#volumes: 
   #logstash:

networks: 
   elastic:
      name: elastic
